project_id = "ijlhgohhpefxbfswmwms"

[functions.chat]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.analyze-photo]
verify_jwt = true

[functions.create-test-partner]
verify_jwt = false

[functions.create-partner-account]
verify_jwt = true

[functions.create-test-partner-with-login]
verify_jwt = false
